package output

import (
	"context"
	"fmt"
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/google/go-github/v62/github"
)

type PRHandler struct {
	GHClient *github.Client
	Logger   *slog.Logger
}

// CreatePR writes updatedContent to AGENTS.md on a new branch and opens a PR.
func (h *PRHandler) CreatePR(
	ctx context.Context,
	repoDir, owner, repo, baseBranch, branchPrefix, taskName, updatedContent string,
	dryRun bool,
) (string, error) {
	branch := branchPrefix + strings.ReplaceAll(repo, "/", "-") + "-" +
		time.Now().UTC().Format("20060102T150405Z")

	if dryRun {
		h.Logger.Info("[dry-run] would create PR",
			"owner", owner, "repo", repo,
			"branch", branch, "content_len", len(updatedContent))
		return "[dry-run] PR not created", nil
	}

	// Create and checkout branch.
	if out, err := runGit(repoDir, "checkout", "-b", branch); err != nil {
		return "", fmt.Errorf("git checkout -b %s: %w\n%s", branch, err, out)
	}

	// Write updated AGENTS.md.
	agentsPath := filepath.Join(repoDir, "AGENTS.md")
	// scan-fix(gosec:G306): 0600 — AGENTS.md is about to be committed anyway;
	// no reason for the working copy to be group/other readable in the interim.
	if err := os.WriteFile(agentsPath, []byte(updatedContent), 0600); err != nil {
		return "", fmt.Errorf("write AGENTS.md: %w", err)
	}

	// Commit.
	if _, err := runGit(repoDir, "add", "AGENTS.md"); err != nil {
		return "", fmt.Errorf("git add: %w", err)
	}
	commitMsg := fmt.Sprintf("docs(agents): update AGENTS.md via %s task\n\nGenerated by ffreis-context-keeper.", taskName)
	if out, err := runGit(repoDir, "commit", "-m", commitMsg); err != nil {
		return "", fmt.Errorf("git commit: %w\n%s", err, out)
	}

	// Push.
	if out, err := runGit(repoDir, "push", "origin", branch); err != nil {
		return "", fmt.Errorf("git push: %w\n%s", err, out)
	}

	// Open PR via GitHub API.
	title := fmt.Sprintf("docs: update AGENTS.md [%s]", taskName)
	body := fmt.Sprintf(
		"Automated AGENTS.md update proposed by [ffreis-context-keeper](https://github.com/FelipeFuhr/ffreis-context-keeper) `%s` task.\n\nPlease review before merging.",
		taskName,
	)
	pr, _, err := h.GHClient.PullRequests.Create(ctx, owner, repo, &github.NewPullRequest{
		Title: github.String(title),
		Body:  github.String(body),
		Head:  github.String(branch),
		Base:  github.String(baseBranch),
	})
	if err != nil {
		return "", fmt.Errorf("create PR: %w", err)
	}
	return pr.GetHTMLURL(), nil
}

// runGit is a package-level var (not a plain func) so tests can substitute a
// fake and exercise CreatePR's branch/commit/push error paths without
// spawning real git processes or touching the network.
var runGit = func(dir string, args ...string) (string, error) {
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	out, err := cmd.CombinedOutput()
	return string(out), err
}
